package com.philips.testdrools;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApplyInfo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "\u59D3\u540D")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "\u5E74\u9F84")
   private java.lang.Integer age;
   @org.kie.api.definition.type.Label(value = "\u5BB6\u5EAD\u4F4F\u5740")
   private com.philips.testdrools.Address famillyAddress;

   public ApplyInfo()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public com.philips.testdrools.Address getFamillyAddress()
   {
      return this.famillyAddress;
   }

   public void setFamillyAddress(com.philips.testdrools.Address famillyAddress)
   {
      this.famillyAddress = famillyAddress;
   }

   public ApplyInfo(java.lang.String name, java.lang.Integer age,
         com.philips.testdrools.Address famillyAddress)
   {
      this.name = name;
      this.age = age;
      this.famillyAddress = famillyAddress;
   }

}